### PR TITLE
Fixes cleverbot

### PR DESCRIPTION
**Pull request by kadmelia**
Uses a fixed cleverbot gem (thx https://github.com/jalada found in  https://github.com/benmanns/cleverbot/issues/7)

### CODE REVIEW

**Comment by Shahor** [comment]
@t0n3 initially PR'ed to use his version because of html staying in the way. 
Does this version also fix this? (ref : #67)

**Comment by kadmelia** [comment]
@jalada's fix is based on @t0n3 work, so i think yes. I tested with this gem quickly and it seems that there is no remaining HTML.

**Comment by Shahor** [comment]
There we go

**Comment by jalada** [comment]
:+1: Glad to inadvertently help!

**Pull request merged**
